// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configuration.proto

package configuration_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestId) Reset()         { *m = RequestId{} }
func (m *RequestId) String() string { return proto.CompactTextString(m) }
func (*RequestId) ProtoMessage()    {}
func (*RequestId) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{0}
}

func (m *RequestId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestId.Unmarshal(m, b)
}
func (m *RequestId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestId.Marshal(b, m, deterministic)
}
func (m *RequestId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestId.Merge(m, src)
}
func (m *RequestId) XXX_Size() int {
	return xxx_messageInfo_RequestId.Size(m)
}
func (m *RequestId) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestId.DiscardUnknown(m)
}

var xxx_messageInfo_RequestId proto.InternalMessageInfo

func (m *RequestId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReplyInfo struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{1}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestId)(nil), "configuration.proto.requestId")
	proto.RegisterType((*ReplyInfo)(nil), "configuration.proto.replyInfo")
}

func init() {
	proto.RegisterFile("configuration.proto", fileDescriptor_415c9e57263f32ab)
}

var fileDescriptor_415c9e57263f32ab = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0x2f, 0x2d, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xc2, 0x26, 0xa8, 0x24, 0xcd, 0xc5, 0x59, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0xe2, 0x99, 0x22,
	0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x94, 0x99, 0xa2,
	0x24, 0x0f, 0x92, 0x2c, 0xc8, 0xa9, 0xf4, 0xcc, 0x4b, 0xcb, 0x17, 0x12, 0xe2, 0x62, 0xc9, 0xcc,
	0x4b, 0xcb, 0x87, 0x4a, 0x83, 0xd9, 0x46, 0x91, 0x5c, 0xec, 0xe9, 0xa9, 0x25, 0x60, 0x69, 0x3f,
	0x2e, 0xae, 0xa2, 0xd4, 0x92, 0xd2, 0xa2, 0x3c, 0x30, 0x4f, 0x4e, 0x0f, 0x8b, 0x65, 0x7a, 0x70,
	0x9b, 0xa4, 0x70, 0xc9, 0x43, 0x2d, 0x53, 0x62, 0x70, 0xd2, 0x89, 0xd2, 0xd2, 0x4f, 0x2f, 0x2a,
	0x48, 0x0e, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x07, 0x2b, 0xd0, 0x05, 0x09, 0xe8, 0x63, 0xd1,
	0x99, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x21, 0xe1, 0xa5, 0xf9,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetInfoClient is the client API for GetInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetInfoClient interface {
	ReturnInfo(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ReplyInfo, error)
}

type getInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGetInfoClient(cc grpc.ClientConnInterface) GetInfoClient {
	return &getInfoClient{cc}
}

func (c *getInfoClient) ReturnInfo(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ReplyInfo, error) {
	out := new(ReplyInfo)
	err := c.cc.Invoke(ctx, "/configuration.proto.getInfo/returnInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetInfoServer is the server API for GetInfo service.
type GetInfoServer interface {
	ReturnInfo(context.Context, *RequestId) (*ReplyInfo, error)
}

// UnimplementedGetInfoServer can be embedded to have forward compatible implementations.
type UnimplementedGetInfoServer struct {
}

func (*UnimplementedGetInfoServer) ReturnInfo(ctx context.Context, req *RequestId) (*ReplyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnInfo not implemented")
}

func RegisterGetInfoServer(s *grpc.Server, srv GetInfoServer) {
	s.RegisterService(&_GetInfo_serviceDesc, srv)
}

func _GetInfo_ReturnInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetInfoServer).ReturnInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configuration.proto.getInfo/ReturnInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetInfoServer).ReturnInfo(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "configuration.proto.getInfo",
	HandlerType: (*GetInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "returnInfo",
			Handler:    _GetInfo_ReturnInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configuration.proto",
}
